//! Canonical backtest configuration and dataset domain model.
//!
//! This module is the single authoritative configuration representation for
//! the Observa MVP (OBS-0003 / OBS-0004). Every component — engine,
//! execution, portfolio, metrics, persistence — consumes the types defined
//! here rather than crate-private configuration structs.
//!
//! The pipeline is:
//!
//! ```text
//! raw config (YAML/JSON)
//!      ↓  strict schema (unknown fields rejected) + explicit defaults
//! BacktestConfig
//!      ↓  `validate()` semantic validation
//! resolved canonical config (deterministically serializable)
//!      ↓  embedded in the persisted run (`run.json`)
//! ```
//!
//! Unit rules that this module enforces by construction:
//! * `units  = quantity_lots × contract_size`
//! * `notional = units × price`
//! * `margin_rate = 1 / leverage` (validation happens in OBS-0005)
//! * monetary value-per-pip/tick is *derived*, never a free input
//!
//! Money is expressed in the instrument quote currency, which must equal the
//! account currency in the MVP (no FX conversion). A configuration where the
//! two differ is rejected, never silently assumed equivalent.

use std::collections::BTreeMap;
use std::fmt;
use std::str::FromStr;

use chrono::{DateTime, Duration, Utc};
use serde::de::{self, Visitor};
use serde::{Deserialize, Deserializer, Serialize, Serializer};

use crate::types::OrderKind;

/// Current configuration schema version.
///
/// Persisted configurations are self-identifying via this marker. No
/// migration framework exists yet; parsers must reject configurations whose
/// version differs from [`CONFIG_VERSION`].
pub const CONFIG_VERSION: u32 = 1;

// ────────────────────────────────────────────────
// Fill mode
// ────────────────────────────────────────────────

/// The canonical MVP fill modes (OBS-0003 §8).
///
/// The historical "fill at the signal bar's open" behavior is deliberately
/// NOT representable here.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum FillMode {
    /// A market order generated by a strategy decision on bar `B` executes at
    /// the close of the same bar `B` (spread/slippage applied to the close).
    BarClose,
    /// A market order generated on bar `B` is queued and executes at the open
    /// of the next bar `B + 1`.
    NextBarOpen,
}

impl fmt::Display for FillMode {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        let s = match self {
            FillMode::BarClose => "BAR_CLOSE",
            FillMode::NextBarOpen => "NEXT_BAR_OPEN",
        };
        write!(f, "{}", s)
    }
}

impl FromStr for FillMode {
    type Err = String;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s.trim().to_uppercase().as_str() {
            "BAR_CLOSE" => Ok(FillMode::BarClose),
            "NEXT_BAR_OPEN" => Ok(FillMode::NextBarOpen),
            other => Err(format!(
                "unknown fill mode '{other}' — expected 'BAR_CLOSE' or 'NEXT_BAR_OPEN'"
            )),
        }
    }
}

// ────────────────────────────────────────────────
// Commission configuration
// ────────────────────────────────────────────────

/// When commission is charged relative to a round trip.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum CommissionMode {
    /// Commission is charged on every fill (entry and exit legs).
    PerSide,
    /// Commission is charged once per completed round trip.
    RoundTrip,
}

/// Canonical commission configuration.
///
/// Both flat and volume-based pricing are representable:
/// * `flat_per_fill` — money charged per fill (or per round trip, per mode),
/// * `rate_per_unit` — money per base unit, so that `$5 / 100,000 units` is
///   `rate_per_unit = 0.00005`.
///
/// The *amount* an execution must charge is
/// `commission = flat_per_fill + rate_per_unit × units` for the units of the
/// fill. Calculation and charging timing belong to OBS-0005/OBS-0006; this
/// configuration only has to represent them unambiguously.
#[derive(Debug, Clone, Copy, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct CommissionConfig {
    /// Charging mode.
    pub mode: CommissionMode,
    /// Fixed money amount per charged event (default: 0).
    #[serde(default = "default_zero")]
    pub flat_per_fill: f64,
    /// Volume-based money rate per base unit (default: 0).
    #[serde(default = "default_zero")]
    pub rate_per_unit: f64,
}

impl Default for CommissionConfig {
    fn default() -> Self {
        Self {
            mode: CommissionMode::PerSide,
            flat_per_fill: 0.0,
            rate_per_unit: 0.0,
        }
    }
}

impl CommissionConfig {
    /// The commission amount attributable to a fill of `units` base units.
    ///
    /// This is the single calculation owner. Whether the amount is *charged*
    /// per side or per round trip is a decision of the charging logic
    /// (OBS-0005/OBS-0006), which must use this method and never recompute
    /// commission independently.
    pub fn amount_for_units(&self, units: f64) -> f64 {
        self.flat_per_fill + self.rate_per_unit * units
    }
}

// ────────────────────────────────────────────────
// Order model configuration
// ────────────────────────────────────────────────

/// Which generic order kinds are enabled for a run.
///
/// The MVP supports MARKET, LIMIT and STOP; protective SL/TP are separate
/// concepts and are always available for open positions.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct OrderModelConfig {
    /// MARKET orders enabled (default: true).
    #[serde(default = "default_true")]
    pub market: bool,
    /// LIMIT orders enabled (default: true).
    #[serde(default = "default_true")]
    pub limit: bool,
    /// STOP orders enabled (default: true).
    #[serde(default = "default_true")]
    pub stop: bool,
}

impl Default for OrderModelConfig {
    fn default() -> Self {
        Self {
            market: true,
            limit: true,
            stop: true,
        }
    }
}

impl OrderModelConfig {
    /// Whether an order of the given kind is enabled.
    pub fn supports(&self, kind: OrderKind) -> bool {
        match kind {
            OrderKind::Market => self.market,
            OrderKind::Limit => self.limit,
            OrderKind::Stop => self.stop,
        }
    }
}

// ────────────────────────────────────────────────
// Account configuration
// ────────────────────────────────────────────────

/// Account-level configuration.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct AccountConfig {
    /// Starting cash balance in account currency (default: 10,000).
    #[serde(default = "default_starting_balance")]
    pub starting_balance: f64,
    /// ISO-4217-style account currency code (default: "USD").
    #[serde(default = "default_currency_usd")]
    pub currency: String,
    /// Account leverage (default: 100). `margin_rate = 1 / leverage`.
    #[serde(default = "default_leverage")]
    pub leverage: f64,
}

impl Default for AccountConfig {
    fn default() -> Self {
        Self {
            starting_balance: default_starting_balance(),
            currency: default_currency_usd(),
            leverage: default_leverage(),
        }
    }
}

// ────────────────────────────────────────────────
// Instrument configuration
// ────────────────────────────────────────────────

/// Instrument configuration — the market the strategy trades.
///
/// Monetary values derived from this config (units, notional, value-per-pip)
/// are computed by [`InstrumentConfig`] methods / [`crate::units`]; they are
/// never independently user-configurable inputs.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct InstrumentConfig {
    /// Instrument identifier, e.g. "EURUSD" (default: "EURUSD").
    #[serde(default = "default_symbol")]
    pub symbol: String,
    /// Base (instrument) currency code, e.g. "EUR".
    #[serde(default = "default_currency_eur")]
    pub base_currency: String,
    /// Quote (pricing) currency code, e.g. "USD".
    #[serde(default = "default_currency_usd")]
    pub quote_currency: String,
    /// Base units per 1 lot/contract (e.g. 100,000 for EURUSD; 1 for a stock).
    #[serde(default = "default_contract_size")]
    pub contract_size: f64,
    /// Price decimal places, e.g. 5 for EURUSD, 2 for a stock. Used to derive
    /// the default tick size when `tick_size` is not provided.
    #[serde(default = "default_price_decimals")]
    pub price_decimals: u32,
    /// Smallest price increment in price units. Derived as
    /// `10^-price_decimals` when omitted.
    #[serde(default)]
    pub tick_size: Option<f64>,
    /// One pip expressed in price units (e.g. 0.0001 for EURUSD). Optional;
    /// required only when pip-based value calculations are used downstream.
    #[serde(default)]
    pub pip_size: Option<f64>,
    /// Minimum tradable quantity, in lots (default: 0.01).
    #[serde(default = "default_min_quantity")]
    pub min_quantity: f64,
    /// Maximum tradable quantity, in lots (default: 100.0).
    #[serde(default = "default_max_quantity")]
    pub max_quantity: f64,
    /// Allowed quantity increment, in lots (default: 0.01).
    #[serde(default = "default_quantity_step")]
    pub quantity_step: f64,
}

impl Default for InstrumentConfig {
    fn default() -> Self {
        Self {
            symbol: default_symbol(),
            base_currency: default_currency_eur(),
            quote_currency: default_currency_usd(),
            contract_size: default_contract_size(),
            price_decimals: default_price_decimals(),
            tick_size: None,
            pip_size: None,
            min_quantity: default_min_quantity(),
            max_quantity: default_max_quantity(),
            quantity_step: default_quantity_step(),
        }
    }
}

impl InstrumentConfig {
    /// Base units for a position of `quantity_lots` lots:
    /// `units = quantity_lots × contract_size`.
    pub fn units(&self, quantity_lots: f64) -> f64 {
        quantity_lots * self.contract_size
    }

    /// Notional value of `quantity_lots` lots at `price`:
    /// `notional = units × price` (quote currency).
    pub fn notional(&self, quantity_lots: f64, price: f64) -> f64 {
        self.units(quantity_lots) * price
    }

    /// The effective tick size in price units: the configured value, or
    /// `10^-price_decimals` when only decimal precision is configured.
    pub fn effective_tick_size(&self) -> Result<f64, ConfigError> {
        match self.tick_size {
            Some(t) => Ok(t),
            None => Ok(10_f64.powi(-(self.price_decimals as i32))),
        }
    }

    /// Money value of one pip per lot = `pip_size × contract_size`.
    ///
    /// Requires `pip_size` to be configured; pip value is a derived quantity
    /// and is never a free input.
    pub fn pip_value_per_lot(&self) -> Result<f64, ConfigError> {
        let pip = self.pip_size.ok_or_else(|| ConfigError::InvalidField {
            field: "instrument.pip_size".into(),
            reason: "pip_size must be configured to derive monetary pip value".into(),
        })?;
        Ok(pip * self.contract_size)
    }
}

// ────────────────────────────────────────────────
// Bar interval
// ────────────────────────────────────────────────

/// The dataset bar interval (timeframe).
///
/// Required later for missing-data gap detection and metric annualization.
/// Serialized as a compact string, e.g. `"15m"`, `"4h"`, `"1d"`, `"1w"`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
pub enum BarInterval {
    /// `N` minutes per bar.
    Minute(u32),
    /// `N` hours per bar.
    Hour(u32),
    /// One day per bar.
    Day,
    /// One week per bar.
    Week,
}

impl BarInterval {
    /// The interval as a `chrono::Duration`, when representable.
    pub fn to_duration(&self) -> Option<Duration> {
        match *self {
            BarInterval::Minute(n) => Duration::try_minutes(i64::from(n)),
            BarInterval::Hour(n) => Duration::try_hours(i64::from(n)),
            BarInterval::Day => Duration::try_days(1),
            BarInterval::Week => Duration::try_days(7),
        }
    }
}

impl fmt::Display for BarInterval {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        let s = match *self {
            BarInterval::Minute(n) => format!("{n}m"),
            BarInterval::Hour(n) => format!("{n}h"),
            BarInterval::Day => "1d".to_string(),
            BarInterval::Week => "1w".to_string(),
        };
        write!(f, "{}", s)
    }
}

impl FromStr for BarInterval {
    type Err = String;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        let s = s.trim();
        let (num, unit) = s.split_at(s.len().saturating_sub(1));
        let unit = unit.to_lowercase();
        let value: u32 = num.parse().map_err(|_| {
            format!("invalid bar interval '{s}' — expected e.g. '15m', '4h', '1d', '1w'")
        })?;
        if value == 0 {
            return Err(format!(
                "invalid bar interval '{s}' — magnitude must be positive"
            ));
        }
        match unit.as_str() {
            "m" => Ok(BarInterval::Minute(value)),
            "h" => Ok(BarInterval::Hour(value)),
            "d" if value == 1 => Ok(BarInterval::Day),
            "w" if value == 1 => Ok(BarInterval::Week),
            _ => Err(format!(
                "invalid bar interval '{s}' — expected e.g. '15m', '4h', '1d', '1w'"
            )),
        }
    }
}

impl Serialize for BarInterval {
    fn serialize<S: Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        serializer.serialize_str(&self.to_string())
    }
}

impl<'de> Deserialize<'de> for BarInterval {
    fn deserialize<D: Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        struct IntervalVisitor;

        impl Visitor<'_> for IntervalVisitor {
            type Value = BarInterval;

            fn expecting(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
                write!(
                    f,
                    "a bar interval string such as \"15m\", \"4h\", \"1d\" or \"1w\""
                )
            }

            fn visit_str<E: de::Error>(self, v: &str) -> Result<BarInterval, E> {
                BarInterval::from_str(v).map_err(E::custom)
            }
        }

        deserializer.deserialize_str(IntervalVisitor)
    }
}

// ────────────────────────────────────────────────
// Dataset configuration
// ────────────────────────────────────────────────

/// Dataset identity and metadata.
///
/// The data loader (OBS-0014+/engine) fills `hash`, `start`, `end` and
/// `bar_count` after loading; the engine embeds the completed metadata in the
/// persisted run.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct DatasetConfig {
    /// Dataset source: a file path or logical name.
    pub source: String,
    /// Content hash (e.g. sha-256 hex) of the dataset, when available.
    #[serde(default)]
    pub hash: Option<String>,
    /// Bar interval of the dataset (required for gap detection/annualization).
    pub interval: BarInterval,
    /// First bar timestamp, when known.
    #[serde(default)]
    pub start: Option<DateTime<Utc>>,
    /// Last bar timestamp, when known.
    #[serde(default)]
    pub end: Option<DateTime<Utc>>,
    /// Number of bars, when known.
    #[serde(default)]
    pub bar_count: Option<u64>,
}

// ────────────────────────────────────────────────
// Strategy configuration
// ────────────────────────────────────────────────

/// Strategy identity and parameters.
///
/// `parameters` uses a `BTreeMap` so serialization is deterministic
/// regardless of insertion order.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct StrategyConfig {
    /// Strategy identity/name (e.g. the strategy class name).
    pub name: String,
    /// Source location (e.g. file path), when known.
    #[serde(default)]
    pub source: Option<String>,
    /// Content hash of the strategy source, when available.
    #[serde(default)]
    pub source_hash: Option<String>,
    /// Resolved strategy parameters.
    #[serde(default)]
    pub parameters: BTreeMap<String, serde_json::Value>,
}

impl Default for StrategyConfig {
    fn default() -> Self {
        Self {
            name: String::new(),
            source: None,
            source_hash: None,
            parameters: BTreeMap::new(),
        }
    }
}

// ────────────────────────────────────────────────
// Execution configuration
// ────────────────────────────────────────────────

/// Execution settings for a run.
///
/// Canonical configuration only; execution *behavior* is owned by the
/// execution model (OBS-0006).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ExecutionConfig {
    /// When market orders generated on a bar execute.
    #[serde(default = "default_fill_mode")]
    pub fill_mode: FillMode,
    /// Fixed spread in price units (default: 0.0002).
    #[serde(default = "default_spread")]
    pub spread: f64,
    /// Fixed slippage in price units (default: 0.0001).
    #[serde(default = "default_slippage")]
    pub slippage: f64,
    /// Commission configuration.
    #[serde(default)]
    pub commission: CommissionConfig,
    /// Which generic order kinds are enabled.
    #[serde(default)]
    pub order_model: OrderModelConfig,
}

impl Default for ExecutionConfig {
    fn default() -> Self {
        Self {
            fill_mode: default_fill_mode(),
            spread: default_spread(),
            slippage: default_slippage(),
            commission: CommissionConfig::default(),
            order_model: OrderModelConfig::default(),
        }
    }
}

// ────────────────────────────────────────────────
// Canonical backtest configuration
// ────────────────────────────────────────────────

/// The canonical configuration of a backtest run.
///
/// One authoritative representation. Strict schema (unknown fields are
/// rejected by serde) plus explicit, deterministic defaults plus semantic
/// validation ([`BacktestConfig::validate`]).
///
/// `dataset` and `strategy` are optional at parse time because their identity
/// (hash, timestamps, parameters) is only known once the run is assembled;
/// the engine fills them before persisting the resolved configuration.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct BacktestConfig {
    /// Configuration schema version; must equal [`CONFIG_VERSION`].
    pub version: u32,
    /// Account configuration.
    #[serde(default)]
    pub account: AccountConfig,
    /// Instrument configuration.
    #[serde(default)]
    pub instrument: InstrumentConfig,
    /// Execution configuration.
    #[serde(default)]
    pub execution: ExecutionConfig,
    /// Dataset identity/metadata, filled by the data layer at run time.
    #[serde(default)]
    pub dataset: Option<DatasetConfig>,
    /// Strategy identity/parameters, filled at run assembly time.
    #[serde(default)]
    pub strategy: Option<StrategyConfig>,
}

impl Default for BacktestConfig {
    fn default() -> Self {
        Self {
            version: CONFIG_VERSION,
            account: AccountConfig::default(),
            instrument: InstrumentConfig::default(),
            execution: ExecutionConfig::default(),
            dataset: None,
            strategy: None,
        }
    }
}

impl BacktestConfig {
    /// Parses a canonical configuration from JSON.
    ///
    /// Unknown fields are rejected by the strict schema. YAML/other formats
    /// can use the same `Deserialize` impl at the consuming edge.
    pub fn from_json_str(input: &str) -> Result<Self, ConfigError> {
        serde_json::from_str(input).map_err(|e| ConfigError::Parse(e.to_string()))
    }

    /// Semantic validation of a parsed configuration.
    ///
    /// Structural validation (unknown fields, enum values) already happens
    /// during parsing; this method validates numeric/currency/relationship
    /// invariants and must be called before the configuration is used.
    pub fn validate(&self) -> Result<(), ConfigError> {
        // Version marker.
        if self.version != CONFIG_VERSION {
            return Err(ConfigError::UnsupportedVersion {
                found: self.version,
                supported: CONFIG_VERSION,
            });
        }

        // Account.
        let f = "account.starting_balance";
        check_finite_positive(self.account.starting_balance, f, false)?;
        validate_currency_code(&self.account.currency, "account.currency")?;
        check_finite_positive(self.account.leverage, "account.leverage", true)?;

        // Instrument.
        if self.instrument.symbol.trim().is_empty() {
            return Err(ConfigError::InvalidField {
                field: "instrument.symbol".into(),
                reason: "must be non-empty".into(),
            });
        }
        validate_currency_code(&self.instrument.base_currency, "instrument.base_currency")?;
        validate_currency_code(&self.instrument.quote_currency, "instrument.quote_currency")?;
        check_finite_positive(
            self.instrument.contract_size,
            "instrument.contract_size",
            true,
        )?;
        if self.instrument.price_decimals == 0 || self.instrument.price_decimals > 12 {
            return Err(ConfigError::InvalidField {
                field: "instrument.price_decimals".into(),
                reason: "must be between 1 and 12".into(),
            });
        }
        if let Some(tick) = self.instrument.tick_size {
            check_finite_positive(tick, "instrument.tick_size", true)?;
        }
        if let Some(pip) = self.instrument.pip_size {
            check_finite_positive(pip, "instrument.pip_size", true)?;
        }
        if let (Some(tick), Some(pip)) = (self.instrument.tick_size, self.instrument.pip_size) {
            if pip < tick {
                return Err(ConfigError::InvalidField {
                    field: "instrument.pip_size".into(),
                    reason: "pip_size must not be smaller than tick_size".into(),
                });
            }
        }
        // Quantity constraints: 0 ≤ min < max and a positive step that fits.
        let min_q = self.instrument.min_quantity;
        let max_q = self.instrument.max_quantity;
        let step = self.instrument.quantity_step;
        if !min_q.is_finite() || min_q < 0.0 {
            return Err(ConfigError::InvalidField {
                field: "instrument.min_quantity".into(),
                reason: "must be finite and >= 0".into(),
            });
        }
        if !max_q.is_finite() || max_q <= min_q {
            return Err(ConfigError::InvalidField {
                field: "instrument.max_quantity".into(),
                reason: "must be finite and greater than min_quantity".into(),
            });
        }
        if !step.is_finite() || step <= 0.0 || step > (max_q - min_q) {
            return Err(ConfigError::InvalidField {
                field: "instrument.quantity_step".into(),
                reason: "must be finite, > 0 and not larger than (max_quantity - min_quantity)"
                    .into(),
            });
        }

        // Execution.
        check_non_negative(self.execution.spread, "execution.spread")?;
        check_non_negative(self.execution.slippage, "execution.slippage")?;
        check_non_negative(
            self.execution.commission.flat_per_fill,
            "execution.commission.flat_per_fill",
        )?;
        check_non_negative(
            self.execution.commission.rate_per_unit,
            "execution.commission.rate_per_unit",
        )?;
        let om = &self.execution.order_model;
        if !om.market && !om.limit && !om.stop {
            return Err(ConfigError::InvalidField {
                field: "execution.order_model".into(),
                reason: "at least one order kind must be enabled".into(),
            });
        }

        // Currency compatibility (no FX conversion in the MVP).
        if self.account.currency != self.instrument.quote_currency {
            return Err(ConfigError::CurrencyMismatch {
                account: self.account.currency.clone(),
                quote: self.instrument.quote_currency.clone(),
            });
        }

        // Dataset.
        if let Some(ds) = &self.dataset {
            if ds.source.trim().is_empty() {
                return Err(ConfigError::InvalidField {
                    field: "dataset.source".into(),
                    reason: "must be non-empty".into(),
                });
            }
            if let (Some(start), Some(end)) = (ds.start, ds.end) {
                if start >= end {
                    return Err(ConfigError::InvalidField {
                        field: "dataset.start".into(),
                        reason: "dataset.start must be earlier than dataset.end".into(),
                    });
                }
            }
        }

        // Strategy.
        if let Some(st) = &self.strategy {
            if st.name.trim().is_empty() {
                return Err(ConfigError::InvalidField {
                    field: "strategy.name".into(),
                    reason: "must be non-empty".into(),
                });
            }
        }

        Ok(())
    }

    /// Returns a resolved copy with the dataset identity attached.
    pub fn with_dataset(mut self, dataset: DatasetConfig) -> Self {
        self.dataset = Some(dataset);
        self
    }

    /// Returns a resolved copy with the strategy identity attached.
    pub fn with_strategy(mut self, strategy: StrategyConfig) -> Self {
        self.strategy = Some(strategy);
        self
    }

    /// Convenience: does this configuration form a resolved (run-ready) config?
    pub fn is_resolved(&self) -> bool {
        self.dataset.is_some() && self.strategy.is_some()
    }
}

// ────────────────────────────────────────────────
// Defaults (explicit, deterministic, documented)
// ────────────────────────────────────────────────
//
// Defaults mirror the repository's established EURUSD sample settings
// (README/config template) translated to the canonical model. Every default
// is serializable into the resolved configuration, so `run.json` always
// records the actual values used.

fn default_true() -> bool {
    true
}

fn default_zero() -> f64 {
    0.0
}

fn default_starting_balance() -> f64 {
    10_000.0
}

fn default_currency_usd() -> String {
    "USD".to_string()
}

fn default_currency_eur() -> String {
    "EUR".to_string()
}

fn default_leverage() -> f64 {
    100.0
}

fn default_symbol() -> String {
    "EURUSD".to_string()
}

fn default_contract_size() -> f64 {
    100_000.0
}

fn default_price_decimals() -> u32 {
    5
}

fn default_min_quantity() -> f64 {
    0.01
}

fn default_max_quantity() -> f64 {
    100.0
}

fn default_quantity_step() -> f64 {
    0.01
}

fn default_fill_mode() -> FillMode {
    FillMode::NextBarOpen
}

fn default_spread() -> f64 {
    0.0002
}

fn default_slippage() -> f64 {
    0.0001
}

// ────────────────────────────────────────────────
// Errors & helpers
// ────────────────────────────────────────────────

/// Errors produced by canonical configuration parsing/validation.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum ConfigError {
    /// The raw input could not be parsed against the strict schema.
    Parse(String),
    /// The configuration schema version is not supported.
    UnsupportedVersion { found: u32, supported: u32 },
    /// A field failed semantic validation.
    InvalidField { field: String, reason: String },
    /// Account currency differs from the instrument quote currency and no FX
    /// conversion is available in the MVP.
    CurrencyMismatch { account: String, quote: String },
}

impl fmt::Display for ConfigError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            ConfigError::Parse(msg) => write!(f, "invalid configuration: {msg}"),
            ConfigError::UnsupportedVersion { found, supported } => write!(
                f,
                "unsupported configuration version {found} (supported: {supported})"
            ),
            ConfigError::InvalidField { field, reason } => {
                write!(f, "invalid configuration field '{field}': {reason}")
            }
            ConfigError::CurrencyMismatch { account, quote } => write!(
                f,
                "account currency '{account}' does not match instrument quote \
                 currency '{quote}'; currency conversion is outside the MVP — \
                 use a matching account currency"
            ),
        }
    }
}

impl std::error::Error for ConfigError {}

/// Validates a currency code: exactly three ASCII letters.
pub fn is_valid_currency_code(code: &str) -> bool {
    code.len() == 3
        && code
            .bytes()
            .all(|b| b.is_ascii_uppercase() && b.is_ascii_alphabetic())
}

fn validate_currency_code(code: &str, field: &str) -> Result<(), ConfigError> {
    if is_valid_currency_code(code) {
        Ok(())
    } else {
        Err(ConfigError::InvalidField {
            field: field.into(),
            reason: format!(
                "'{code}' is not a valid currency code (expected 3 uppercase ASCII letters)"
            ),
        })
    }
}

fn check_finite_positive(
    value: f64,
    field: &str,
    strictly_positive: bool,
) -> Result<(), ConfigError> {
    let ok = if strictly_positive {
        value.is_finite() && value > 0.0
    } else {
        value.is_finite() && value >= 0.0
    };
    if ok {
        Ok(())
    } else {
        Err(ConfigError::InvalidField {
            field: field.into(),
            reason: format!(
                "must be a finite {sign} number",
                sign = if strictly_positive {
                    "positive"
                } else {
                    "non-negative"
                }
            ),
        })
    }
}

fn check_non_negative(value: f64, field: &str) -> Result<(), ConfigError> {
    check_finite_positive(value, field, false)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn valid_json() -> String {
        r#"{
            "version": 1,
            "account": { "starting_balance": 10000.0, "currency": "USD", "leverage": 100.0 },
            "instrument": {
                "symbol": "EURUSD", "base_currency": "EUR", "quote_currency": "USD",
                "contract_size": 100000.0, "price_decimals": 5,
                "min_quantity": 0.01, "max_quantity": 100.0, "quantity_step": 0.01
            },
            "execution": {
                "fill_mode": "NEXT_BAR_OPEN",
                "spread": 0.0002, "slippage": 0.0001,
                "commission": { "mode": "PER_SIDE", "flat_per_fill": 7.0, "rate_per_unit": 0.0 },
                "order_model": { "market": true, "limit": true, "stop": true }
            }
        }"#
        .to_string()
    }

    #[test]
    fn valid_configuration_parses_and_validates() {
        let cfg = BacktestConfig::from_json_str(&valid_json()).unwrap();
        assert!(cfg.validate().is_ok());
        assert_eq!(cfg.account.currency, "USD");
        assert_eq!(cfg.instrument.quote_currency, "USD");
        assert_eq!(cfg.execution.fill_mode, FillMode::NextBarOpen);
    }

    #[test]
    fn unknown_fields_are_rejected() {
        let mut doc: serde_json::Value = serde_json::from_str(&valid_json()).unwrap();
        doc["account"]["unknown_key"] = serde_json::json!(1);
        let err = BacktestConfig::from_json_str(&doc.to_string()).unwrap_err();
        assert!(matches!(err, ConfigError::Parse(_)));
    }

    #[test]
    fn legacy_fields_are_rejected_not_ignored() {
        // Old broker-assumption keys must not silently parse into the
        // canonical model.
        let mut doc: serde_json::Value = serde_json::from_str(&valid_json()).unwrap();
        doc["instrument"]["pip_value"] = serde_json::json!(10.0);
        assert!(BacktestConfig::from_json_str(&doc.to_string()).is_err());

        let mut doc2: serde_json::Value = serde_json::from_str(&valid_json()).unwrap();
        doc2["account"]["margin_rate"] = serde_json::json!(0.01);
        assert!(BacktestConfig::from_json_str(&doc2.to_string()).is_err());
    }

    #[test]
    fn yaml_unknown_fields_are_rejected() {
        let yaml = r#"
version: 1
account:
  currency: USD
instrument:
  symbol: EURUSD
  base_currency: EUR
  quote_currency: USD
  contract_size: 100000
execution:
  fill_mode: NEXT_BAR_OPEN
  spread: 0.0002
  slippage: 0.0001
  commission: { mode: PER_SIDE }
bogus_section:
  anything: true
"#;
        let result: Result<BacktestConfig, _> = serde_yaml::from_str(yaml);
        assert!(result.is_err());
    }

    #[test]
    fn defaults_are_explicit_and_deterministic() {
        let cfg = BacktestConfig::default();
        // Defaults are documented sample defaults, fully materialized.
        assert_eq!(cfg.version, CONFIG_VERSION);
        assert_eq!(cfg.account.starting_balance, 10_000.0);
        assert_eq!(cfg.account.currency, "USD");
        assert_eq!(cfg.account.leverage, 100.0);
        assert_eq!(cfg.instrument.symbol, "EURUSD");
        assert_eq!(cfg.instrument.contract_size, 100_000.0);
        assert_eq!(cfg.execution.fill_mode, FillMode::NextBarOpen);
        assert!(cfg.execution.order_model.supports(OrderKind::Market));
        assert!(cfg.execution.order_model.supports(OrderKind::Limit));
        assert!(cfg.execution.order_model.supports(OrderKind::Stop));
        assert_eq!(cfg.execution.commission.mode, CommissionMode::PerSide);
        assert!(cfg.validate().is_ok());

        // Defaults serialize into the resolved representation.
        let s1 = serde_json::to_string(&cfg).unwrap();
        let s2 = serde_json::to_string(&BacktestConfig::default()).unwrap();
        assert_eq!(s1, s2);
    }

    #[test]
    fn defaults_apply_on_missing_fields() {
        // Minimal config: everything else falls back to explicit defaults.
        let json = r#"{"version": 1}"#;
        let cfg = BacktestConfig::from_json_str(json).unwrap();
        assert!(cfg.validate().is_ok());
        assert_eq!(cfg.account.currency, "USD");
        assert_eq!(cfg.instrument.symbol, "EURUSD");
    }

    #[test]
    fn currency_mismatch_is_rejected() {
        let mut doc: serde_json::Value = serde_json::from_str(&valid_json()).unwrap();
        doc["account"]["currency"] = serde_json::json!("KES");
        let cfg = BacktestConfig::from_json_str(&doc.to_string()).unwrap();
        let err = cfg.validate().unwrap_err();
        assert!(matches!(err, ConfigError::CurrencyMismatch { .. }));
        assert!(err.to_string().contains("KES"));
    }

    #[test]
    fn invalid_leverage_is_rejected() {
        // Zero/negative leverage (JSON-representable).
        for bad in [0.0, -1.0] {
            let mut doc: serde_json::Value = serde_json::from_str(&valid_json()).unwrap();
            doc["account"]["leverage"] = serde_json::json!(bad);
            let cfg = BacktestConfig::from_json_str(&doc.to_string()).unwrap();
            assert!(cfg.validate().is_err(), "leverage {bad} must fail");
        }
        // NaN/Infinity are not JSON-representable; validate them directly.
        for bad in [f64::NAN, f64::INFINITY, f64::NEG_INFINITY] {
            let cfg = BacktestConfig {
                account: AccountConfig {
                    leverage: bad,
                    ..AccountConfig::default()
                },
                ..BacktestConfig::default()
            };
            assert!(cfg.validate().is_err(), "leverage {bad} must fail");
        }
    }

    #[test]
    fn invalid_contract_size_is_rejected() {
        for bad in [0.0, -100.0] {
            let mut doc: serde_json::Value = serde_json::from_str(&valid_json()).unwrap();
            doc["instrument"]["contract_size"] = serde_json::json!(bad);
            let cfg = BacktestConfig::from_json_str(&doc.to_string()).unwrap();
            assert!(cfg.validate().is_err(), "contract_size {bad} must fail");
        }
    }

    #[test]
    fn invalid_quantity_constraints_are_rejected() {
        // max <= min
        let mut doc: serde_json::Value = serde_json::from_str(&valid_json()).unwrap();
        doc["instrument"]["min_quantity"] = serde_json::json!(5.0);
        doc["instrument"]["max_quantity"] = serde_json::json!(5.0);
        assert!(BacktestConfig::from_json_str(&doc.to_string())
            .unwrap()
            .validate()
            .is_err());

        // step larger than the range
        let mut doc2: serde_json::Value = serde_json::from_str(&valid_json()).unwrap();
        doc2["instrument"]["min_quantity"] = serde_json::json!(0.01);
        doc2["instrument"]["max_quantity"] = serde_json::json!(0.02);
        doc2["instrument"]["quantity_step"] = serde_json::json!(0.05);
        assert!(BacktestConfig::from_json_str(&doc2.to_string())
            .unwrap()
            .validate()
            .is_err());

        // negative step
        let mut doc3: serde_json::Value = serde_json::from_str(&valid_json()).unwrap();
        doc3["instrument"]["quantity_step"] = serde_json::json!(-0.01);
        assert!(BacktestConfig::from_json_str(&doc3.to_string())
            .unwrap()
            .validate()
            .is_err());
    }

    #[test]
    fn fill_mode_both_modes_parse() {
        for (text, mode) in [
            ("BAR_CLOSE", FillMode::BarClose),
            ("NEXT_BAR_OPEN", FillMode::NextBarOpen),
        ] {
            let mut doc: serde_json::Value = serde_json::from_str(&valid_json()).unwrap();
            doc["execution"]["fill_mode"] = serde_json::json!(text);
            let cfg = BacktestConfig::from_json_str(&doc.to_string()).unwrap();
            assert_eq!(cfg.execution.fill_mode, mode);
            assert!(cfg.validate().is_ok());
        }
    }

    #[test]
    fn invalid_fill_mode_is_rejected_at_parse() {
        let mut doc: serde_json::Value = serde_json::from_str(&valid_json()).unwrap();
        doc["execution"]["fill_mode"] = serde_json::json!("THIS_BAR_OPEN");
        assert!(BacktestConfig::from_json_str(&doc.to_string()).is_err());
    }

    #[test]
    fn fill_mode_from_str_rejects_signal_bar_open() {
        assert!(FillMode::from_str("THIS_BAR_OPEN").is_err());
        assert!(FillMode::from_str("bar close").is_err());
        assert_eq!(FillMode::from_str("bar_close"), Ok(FillMode::BarClose));
        assert_eq!(
            FillMode::from_str("next_bar_open"),
            Ok(FillMode::NextBarOpen)
        );
    }

    #[test]
    fn order_model_represents_market_limit_stop() {
        let om = OrderModelConfig::default();
        assert!(om.supports(OrderKind::Market));
        assert!(om.supports(OrderKind::Limit));
        assert!(om.supports(OrderKind::Stop));

        let disabled = OrderModelConfig {
            market: false,
            limit: false,
            stop: false,
        };
        assert!(!disabled.supports(OrderKind::Market));
    }

    #[test]
    fn commission_modes_and_volume_roundtrip() {
        // $5 per 100,000 units = 0.00005 per unit.
        let cfg = CommissionConfig {
            mode: CommissionMode::PerSide,
            flat_per_fill: 0.0,
            rate_per_unit: 0.00005,
        };
        let json = serde_json::to_string(&cfg).unwrap();
        let back: CommissionConfig = serde_json::from_str(&json).unwrap();
        assert_eq!(back, cfg);
        assert_eq!(back.amount_for_units(100_000.0), 5.0);
        assert_eq!(back.amount_for_units(50_000.0), 2.5);

        let rt = CommissionConfig {
            mode: CommissionMode::RoundTrip,
            flat_per_fill: 7.0,
            rate_per_unit: 0.0,
        };
        let json = serde_json::to_string(&rt).unwrap();
        assert!(json.contains("ROUND_TRIP"));
        let back: CommissionConfig = serde_json::from_str(&json).unwrap();
        assert_eq!(back, rt);
        assert_eq!(back.amount_for_units(1_000_000.0), 7.0);
    }

    #[test]
    fn resolved_configuration_is_deterministic() {
        let base = BacktestConfig::from_json_str(&valid_json()).unwrap();
        let dataset = DatasetConfig {
            source: "data/EURUSD_M15.csv".to_string(),
            hash: Some("abc123".to_string()),
            interval: BarInterval::Minute(15),
            start: None,
            end: None,
            bar_count: Some(1500),
        };
        let strategy = StrategyConfig {
            name: "EMACrossover".to_string(),
            source: Some("strategies/ema_crossover.py".to_string()),
            source_hash: Some("def456".to_string()),
            parameters: BTreeMap::from([
                ("fast_period".to_string(), serde_json::json!(5)),
                ("slow_period".to_string(), serde_json::json!(20)),
            ]),
        };

        let resolved_a = base
            .clone()
            .with_dataset(dataset.clone())
            .with_strategy(strategy.clone());
        let resolved_b = base.with_dataset(dataset).with_strategy(strategy);
        assert!(resolved_a.validate().is_ok());
        assert!(resolved_a.is_resolved());

        // Identical inputs → byte-identical serialized output.
        assert_eq!(
            serde_json::to_string(&resolved_a).unwrap(),
            serde_json::to_string(&resolved_b).unwrap()
        );
        // And no volatile content is present.
        let s = serde_json::to_string(&resolved_a).unwrap();
        assert!(!s.contains("00000000-0000"));
    }

    #[test]
    fn dataset_interval_survives_roundtrip() {
        for interval in [
            BarInterval::Minute(15),
            BarInterval::Hour(4),
            BarInterval::Day,
            BarInterval::Week,
        ] {
            let json = serde_json::to_string(&interval).unwrap();
            let back: BarInterval = serde_json::from_str(&json).unwrap();
            assert_eq!(back, interval, "roundtrip for {json}");
        }

        let ds = DatasetConfig {
            source: "x.csv".into(),
            hash: None,
            interval: BarInterval::Minute(15),
            start: None,
            end: None,
            bar_count: None,
        };
        let json = serde_json::to_string(&ds).unwrap();
        let back: DatasetConfig = serde_json::from_str(&json).unwrap();
        assert_eq!(back.interval, BarInterval::Minute(15));
        assert_eq!(back.interval.to_string(), "15m");
        assert_eq!(BarInterval::Day.to_string(), "1d");
    }

    #[test]
    fn config_version_marker_present_and_stable() {
        assert_eq!(CONFIG_VERSION, 1);
        let cfg = BacktestConfig::default();
        let json = serde_json::to_value(&cfg).unwrap();
        assert_eq!(json["version"], 1);

        // Unsupported versions are rejected.
        let mut doc: serde_json::Value = serde_json::from_str(&valid_json()).unwrap();
        doc["version"] = serde_json::json!(999);
        let cfg = BacktestConfig::from_json_str(&doc.to_string()).unwrap();
        assert!(matches!(
            cfg.validate(),
            Err(ConfigError::UnsupportedVersion { .. })
        ));
    }

    #[test]
    fn instrument_derivations_are_correct() {
        let cfg = InstrumentConfig::default();
        // units = quantity_lots × contract_size
        assert_eq!(cfg.units(1.0), 100_000.0);
        // notional = units × price
        let notional = cfg.notional(1.0, 1.10);
        assert!((notional - 110_000.0).abs() < 0.001);
        // tick derived from decimals when not configured: 10^-5 = 0.00001
        assert!((cfg.effective_tick_size().unwrap() - 0.00001).abs() < 1e-12);
        // pip value is derived (pip_size × contract_size), never a free input
        let cfg_with_pip = InstrumentConfig {
            pip_size: Some(0.0001),
            ..cfg
        };
        assert!((cfg_with_pip.pip_value_per_lot().unwrap() - 10.0).abs() < 1e-9);
        assert!(InstrumentConfig::default().pip_value_per_lot().is_err());
    }

    #[test]
    fn invalid_currency_codes_are_rejected() {
        for bad in ["usd", "US", "USDD", "U1D", "us!", ""] {
            assert!(!is_valid_currency_code(bad), "{bad} must be invalid");
        }
        for good in ["USD", "EUR", "KES", "JPY"] {
            assert!(is_valid_currency_code(good), "{good} must be valid");
        }
    }
}
