[package]
name = "observa-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono    = { version = "0.4", features = ["serde"] }
serde_json = "1.0"
tiny_http  = "0.12"
uuid       = { version = "1.0", features = ["v4", "serde"] }
serde_yaml = "0.9"
serde      = { version = "1.0", features = ["derive"] }
observa-core      = { path = "../observa-core" }
observa-data      = { path = "../observa-data" }
observa-engine    = { path = "../observa-engine" }
observa-metrics   = { path = "../observa-metrics" }
observa-python    = { path = "../observa-python" }
