"""OBS-AI-01R — deterministic canonical regression baseline.

Run against an installed Observa wheel:

    python python/tests/test_canonical_baseline.py

This is the project's canonical economic regression oracle. It uses a
checked-in, fully deterministic synthetic dataset
(``python/tests/fixtures/canonical_m15.csv``, regenerated by
``generate_canonical_dataset.py``) — never a rolling/live market file — so the
expected numbers are stable forever.

A regression fails this test with an explicit expected/actual table for the
key economics (not just an opaque hash). The metrics digest is supplemental.

See ``docs/engineering/TESTING.md`` for the baseline's source of truth.
"""

import hashlib
import importlib.util
import json
import os
import sys
import tempfile

import observa
from observa.samples.sample_strategy import SampleEma

HERE = os.path.dirname(os.path.abspath(__file__))
FIXTURE = os.path.join(HERE, "fixtures", "canonical_m15.csv")
GENERATOR = os.path.join(HERE, "fixtures", "generate_canonical_dataset.py")

TOL = 1e-9

# ── Canonical regression case ───────────────────────────────────
# dataset fixture : python/tests/fixtures/canonical_m15.csv (1500 M15 bars)
# strategy        : observa.samples.sample_strategy.SampleEma (fast=5, slow=20)
# fill mode       : next_bar_open
# spread          : 0.0002
# slippage        : 0.0001
# commission      : 7.0 (round trip, flat)
# interval        : 15m
# account/instrument: Observa defaults (10000 USD, 100:1, 100k contract)
CANONICAL = dict(
    fill_mode=observa.NEXT_BAR_OPEN,
    spread=0.0002,
    slippage=0.0001,
    commission=7.0,
    commission_mode=observa.ROUND_TRIP,
    interval="15m",
    params={"fast": 5, "slow": 20},
    strategy_name="SampleEma",
)

EXPECTED = {
    "total_bars": 1500,
    "events": 4862,
    "trades": 47,
    "orders": 88,
    "fills": 95,
    "open_positions": 1,
    "final_balance": 7718.000000000193,
    "final_equity": 7737.0000000002065,
}

EXPECTED_METRICS = {
    "total_trades": 47,
    "winning_trades": 7,
    "losing_trades": 40,
    "open_positions_remaining": 1,
    "win_rate_pct": 14.893617021276595,
    "total_return_pct": -22.629999999997935,
    "annualised_return_pct": -4.218817103379646,
    "max_drawdown_pct": 35.615097026881344,
    "current_drawdown_pct": 31.12871639665119,
    "sharpe_ratio": -0.4797045550240251,
    "calmar_ratio": -0.1184558643823262,
    "avg_win": 756.0000000000025,
    "avg_loss": 189.34999999999562,
    "profit_factor": 0.6987060998151756,
    "expectancy": -48.5531914893576,
    "largest_win": 2493.9999999999977,
    "largest_loss": 446.99999999999596,
}
EXPECTED_METRICS_DIGEST = "6c23dc6c0c0630e66bd21290c47f48bb00ac6612d66b2b7047df7a191ea77b44"
EXPECTED_METRIC_TIMESTAMPS = {
    "max_drawdown_start": "2024-01-01T11:45:00Z",
    "max_drawdown_end": "2024-01-11T21:30:00Z",
}

PASSED, FAILED = [], []


def check(label, ok, detail=""):
    (PASSED if ok else FAILED).append(label)
    print(("PASS " if ok else "FAIL ") + label + ("" if ok else " :: " + str(detail)))


def _diff_table(title, expected, actual):
    lines = ["", "  " + title, "  %-14s %-26s %s" % ("field", "expected", "actual")]
    for key in expected:
        exp, act = expected[key], actual.get(key)
        same = _close(exp, act)
        lines.append("  %-14s %-26r %r%s" % (key, exp, act, "" if same else "   <-- DIFFERS"))
    print("\n".join(lines))


def _close(a, b):
    if isinstance(a, float) or isinstance(b, float):
        try:
            return abs(float(a) - float(b)) <= TOL
        except (TypeError, ValueError):
            return False
    return a == b


def _digest(value):
    return hashlib.sha256(
        json.dumps(value, sort_keys=True, separators=(",", ":")).encode()
    ).hexdigest()


def _run(output=None):
    cfg = observa.Config(dataset_source=FIXTURE, **CANONICAL)
    return observa.run(SampleEma(), FIXTURE, config=cfg, output=output)


def test_fixture_is_reproducible():
    """The committed fixture must equal a fresh deterministic regeneration."""
    spec = importlib.util.spec_from_file_location("canonical_fixture_gen", GENERATOR)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    regenerated = "timestamp,open,high,low,close,volume\n" + "\n".join(module.generate()) + "\n"
    committed = open(FIXTURE, "r", encoding="utf-8").read()
    check(
        "fixture file matches deterministic regeneration",
        regenerated == committed,
        "regenerate with: python %s" % os.path.relpath(GENERATOR),
    )
    check("fixture has 1500 bars", len(committed.strip().splitlines()) - 1 == 1500)


def test_canonical_baseline(tmp_dir):
    result = _run(output=os.path.join(tmp_dir, "canonical"))
    summary = result.summary()
    actual = {
        "total_bars": summary["total_bars"],
        "events": len(result.events),
        "trades": len(result.trades),
        "orders": len(result.orders),
        "fills": len(result.fills),
        "open_positions": result.open_positions,
        "final_balance": result.final_balance,
        "final_equity": result.final_equity,
    }
    for key, expected in EXPECTED.items():
        check("canonical %s == %r" % (key, expected), _close(expected, actual[key]), actual[key])
    if any(not _close(EXPECTED[k], actual[k]) for k in EXPECTED):
        _diff_table("CANONICAL ECONOMICS REGRESSION", EXPECTED, actual)

    metrics = result.metrics
    for key, expected in EXPECTED_METRICS.items():
        got = metrics.get(key)
        check("metric %s == %r" % (key, expected), _close(expected, got), got)
    for key, expected in EXPECTED_METRIC_TIMESTAMPS.items():
        check("metric %s == %r" % (key, expected), metrics.get(key) == expected, metrics.get(key))

    digest = _digest(metrics)
    check("metrics digest stable", digest == EXPECTED_METRICS_DIGEST, digest)
    if digest != EXPECTED_METRICS_DIGEST:
        print("  expected digest: %s" % EXPECTED_METRICS_DIGEST)
        print("  actual digest:   %s" % digest)
        print("  (review metric values above before accepting a new baseline)")
    return result, metrics


def test_determinism(first_result, first_metrics):
    second = _run()
    actual = {
        "events": len(second.events),
        "trades": len(second.trades),
        "orders": len(second.orders),
        "fills": len(second.fills),
        "open_positions": second.open_positions,
        "final_balance": second.final_balance,
        "final_equity": second.final_equity,
    }
    repeated = {k: actual[k] for k in ("events", "trades", "orders", "fills",
                                       "open_positions", "final_balance", "final_equity")}
    check("repeated run reproduces counts/balances", all(
        _close(EXPECTED[k], repeated[k]) for k in
        ("events", "trades", "orders", "fills", "open_positions", "final_balance", "final_equity")
    ), repeated)
    check("repeated run reproduces metrics", _digest(second.metrics) == _digest(first_metrics),
          _digest(second.metrics))


def main():
    check("observa.__version__ == 0.1.1", observa.__version__ == "0.1.1", observa.__version__)
    test_fixture_is_reproducible()
    tmp_dir = tempfile.mkdtemp(prefix="observa-canonical-")
    result, metrics = test_canonical_baseline(tmp_dir)
    test_determinism(result, metrics)
    import shutil
    shutil.rmtree(tmp_dir, ignore_errors=True)
    print("\n%d checks passed, %d failed" % (len(PASSED), len(FAILED)))
    return 1 if FAILED else 0


if __name__ == "__main__":
    sys.exit(main())
